# Generated by Django 4.2.1 on 2023-08-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_articles_user_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='user_id_number',
            field=models.IntegerField(),
        ),
    ]
