# Generated by Django 4.2.5 on 2023-09-22 14:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_feedbacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments_layer1',
            name='dislikes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=list, size=None),
        ),
        migrations.AddField(
            model_name='comments_layer1',
            name='likes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=list, size=None),
        ),
    ]
