# Generated by Django 4.2.5 on 2023-09-25 18:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comments_layer1_dislikes_comments_layer1_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments_layer2',
            name='dislikes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=list, size=None),
        ),
        migrations.AddField(
            model_name='comments_layer2',
            name='likes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=list, size=None),
        ),
    ]
