# Generated by Django 4.2.5 on 2023-10-19 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comments_layer2_dislikes_comments_layer2_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments_layer2',
            old_name='likes',
            new_name='likes2',
        ),
    ]
