# Generated by Django 4.2.5 on 2023-10-19 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_likes_comments_layer2_likes2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments_layer2',
            old_name='likes2',
            new_name='likes',
        ),
    ]
