# Generated by Django 4.2.5 on 2023-10-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_likes2_comments_layer2_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='status',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='comments_layer1',
            name='status',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='comments_layer2',
            name='status',
            field=models.TextField(default=''),
        ),
    ]
