# Generated by Django 4.2.5 on 2023-11-02 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_reaction_notification_comment_layer2_notification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_layer1_notification',
            name='type_of_comment',
        ),
        migrations.RemoveField(
            model_name='comment_layer1_notification',
            name='type_of_notification',
        ),
        migrations.RemoveField(
            model_name='comment_layer2_notification',
            name='type_of_comment',
        ),
        migrations.RemoveField(
            model_name='comment_layer2_notification',
            name='type_of_notification',
        ),
        migrations.RemoveField(
            model_name='reaction_notification',
            name='type_of_notification',
        ),
    ]
