# Generated by Django 4.2.5 on 2023-11-04 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_comment_layer1_notification_type_of_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_layer1_notification',
            name='comment_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.comments_layer1'),
        ),
        migrations.AlterField(
            model_name='comment_layer2_notification',
            name='comment_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.comments_layer2'),
        ),
    ]
