# Generated by Django 4.2.5 on 2023-11-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notifications',
            field=models.TextField(default=''),
        ),
    ]
