# Generated by Django 4.2.5 on 2023-11-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_customuser_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='notifications',
            field=models.IntegerField(default=0),
        ),
    ]
